package come.has.winther.puber;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.support.v4.app.ActivityCompat;
import android.support.v4.app.FragmentActivity;
import android.os.Bundle;
import android.util.Log;

import com.google.android.gms.location.FusedLocationProviderClient;
import com.google.android.gms.location.LocationCallback;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;
import com.google.android.gms.tasks.OnSuccessListener;

import java.util.ArrayList;

public class MapsActivity extends FragmentActivity implements OnMapReadyCallback {

    private String DEBUG = "MapsActivity";

    private GoogleMap mMap;
    private ArrayList<User> locations;
    private Location mCurrentLocation;
    private Marker ownMarker;

    private boolean userMovedView = false;

    // Location of user
    private FusedLocationProviderClient mFusedLocationClient;
    private LocationListener locationListener;
    private LocationManager locationManager;

    // Background service
    BackgroundService bgService; // For queueing data with mServiceIntent (enqueueWork(getContext(), BackgroundService.class, ID, mServiceIntent)
    Intent mServiceIntent; // for adding data to process


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_maps);

        locations = BackgroundService.getToiletsNearby(new LatLng(56.158, 10.2));
        // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);

        // If the user has turned of GPS in the meantime (auto generated by intelliJ)
        mFusedLocationClient = LocationServices.getFusedLocationProviderClient(this);
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {

            Utilities.checkForGPSPermission(this);
            return;
        }

        locationManager = (LocationManager) this.getSystemService(LOCATION_SERVICE);

        locationListener = new LocationListener() {
            @Override
            public void onLocationChanged(Location location) {
                Log.d(DEBUG, "Location changed! (" + location.getLatitude() + ", " + location.getLongitude() + ")");
                // Get new closest toilets from this location
                mCurrentLocation = location;

                // The user haven't moved the view of the map ie. we want to update the center whenever he/she moves
                if (!userMovedView) {
                    // Center the camera to the new location with the current zoom level
                    LatLng currentPos = new LatLng(location.getLatitude(), location.getLongitude());
                    mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(currentPos, mMap.getCameraPosition().zoom));
                    if (ownMarker != null)
                        ownMarker.remove();

                    ownMarker = mMap.addMarker(new MarkerOptions().position(currentPos).title("This is you!"));
                }
            }

            @Override
            public void onStatusChanged(String provider, int status, Bundle extras) {

            }

            @Override
            public void onProviderEnabled(String provider) {

            }

            @Override
            public void onProviderDisabled(String provider) {

            }
        };

        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, locationListener);

        mFusedLocationClient.getLastLocation().addOnSuccessListener(this, new OnSuccessListener<Location>() {
            @Override
            public void onSuccess(Location location) {
                if (location != null) {
                    // We know know the user's location
                    mCurrentLocation = location;
                    Log.d(DEBUG, "Coordinates are: (" + location.getLatitude() + ", " + location.getLongitude() + ")");

                    // Add a marker in Sydney and move the camera
                    LatLng currentPos = new LatLng(mCurrentLocation.getLatitude(), mCurrentLocation.getLongitude());
                    float zoomLevel = 16.0f;
                    ownMarker = mMap.addMarker(new MarkerOptions().position(currentPos).title("This is you!"));

                    mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(currentPos, zoomLevel));
                }
            }
        });
    }


    /**
     * Manipulates the map once available.
     * This callback is triggered when the map is ready to be used.
     * This is where we can add markers or lines, add listeners or move the camera. In this case,
     * we just add a marker near Sydney, Australia.
     * If Google Play services is not installed on the device, the user will be prompted to install
     * it inside the SupportMapFragment. This method will only be triggered once the user has
     * installed Google Play services and returned to the app.
     */
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        setMarkers(locations);

        mMap.setOnMarkerClickListener(new GoogleMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(Marker marker) {
                // When a marker is clicked, the title (the owner of the toilet) is selected
                String nameOfMarker = marker.getTitle();

                // Open a new fragment
                // TODO THIS IS WHERE TROELS PUTS HIS CODE TO OPEN A NEW FRAGMENT

                // Returns true so that default behavior does not occur
                // (move to the marker and an info windows appears
                return true;

            }
        });
    }

    public void setMarkers(ArrayList<User> usrs) {
        MarkerOptions options = new MarkerOptions();
        for (int i = 0; i < usrs.size(); i++) {
            User currentUser = usrs.get(i);

            options.position(new LatLng(currentUser.getLatitude(), currentUser.getLongitude()))
                    .title(currentUser.getName())
                    .icon(BitmapDescriptorFactory.fromResource(R.drawable.usericon));

            mMap.addMarker(options);

            Log.d(DEBUG, "Added " + currentUser.getName() + " to map with coordinates: "
            + "(" + currentUser.getLatitude() + ", " + currentUser.getLongitude() + ")");
        }
    }
    
}
